### ISSUE TITLE
Error running base template

### ISSUE THREAD

**Issue by paulsymphony** [samme/brunch-phaser-typescript#1]
I get this error when installing and using npm run start:
"WEBGL_RENDERER is not defined..."

**Comment by samme** [comment]
What does the stack trace show?

**Comment by paulsymphony** [comment]
SpriteRender.js:14 Uncaught ReferenceError: WEBGL_RENDERER is not defined
    at SpriteRender.js:14
    at SpriteRender.js:30
    at initModule (vendor.js:42)
    at require (vendor.js:59)
    at expanded (vendor.js:34)
    at vendor.js:148
    at Sprite.js:14
    at Sprite.js:153
    at initModule (vendor.js:42)
    at require (vendor.js:59)

**Comment by samme** [comment]
> at require (vendor.js:59)

What's the statement here?

**Comment by samme** [comment]
Nvm, I found it.

**Comment by paulsymphony** [comment]
awesome - thank you!
